/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type FollowUp = {
  title: string;
  message: string;
  sentBy: string;
};

export type Items = {
  messengerPigeon: ProductCard;
  podium: ProductCard;
  liveServices: ProductCard;
};

export type Form = {
  nameLabel: string;
  namePlaceholder: string;
  emailLabel: string;
  emailPlaceholder: string;
  messageLabel: string;
  messagePlaceholder: string;
  submit: string;
};

export type ContactSection = {
  _type: "contactSection";
  title: string;
  description: string;
  partnersLabel: string;
  partners: Array<{
    _key: string;
  } & ImageWithAlt>;
  form: Form;
};

export type BlogSection = {
  _type: "blogSection";
  label: string;
  title: string;
  nextPage: string;
};

export type ProductsSection = {
  _type: "productsSection";
  label: string;
  title: string;
  description: string;
  learnMore: string;
  items: Items;
};

export type ValuesSection = {
  _type: "valuesSection";
  label: string;
  title: string;
  image: ImageWithAlt;
  items: Array<{
    title: string;
    description: string;
    _type: "valueItem";
    _key: string;
  }>;
};

export type HeroSection = {
  _type: "heroSection";
  label: string;
  title: string;
  description: string;
  primaryCta: string;
  secondaryCta: string;
  trustedBy: string;
  pauseVideo: string;
  playVideo: string;
  avatars: Array<{
    _key: string;
  } & ImageWithAlt>;
  teamImage: ImageWithAlt;
  followUp: FollowUp;
};

export type ProductCard = {
  _type: "productCard";
  title: string;
  description: string;
  image: ImageWithAlt;
};

export type NavItem = {
  _type: "navItem";
  label: string;
  description: string;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type ImageWithAlt = {
  _type: "imageWithAlt";
  asset?: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt: string;
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  category: string;
  date: string;
  image: ImageWithAlt;
  url: string;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  language?: string;
  meta: {
    title: string;
    description: string;
    ogImage: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
  };
  nav: {
    logoAlt: string;
    openMenu: string;
    closeMenu: string;
    getStarted: string;
    organizations: {
      label: string;
      columns: {
        products: {
          label: string;
          items: {
            messengerPigeon: NavItem;
            podium: NavItem;
            liveServices: NavItem;
          };
        };
        resources: {
          label: string;
          items: {
            blog: NavItem;
            help: NavItem;
            security: NavItem;
          };
        };
        start: {
          label: string;
          items: {
            login: NavItem;
            bookCall: NavItem;
          };
        };
      };
      promo: {
        label: string;
        image: ImageWithAlt;
      };
    };
    students: {
      label: string;
      columnLabel: string;
      items: {
        messengerPigeon: string;
        help: string;
        download: string;
        helpAgain: string;
        login: string;
      };
      promo: {
        label: string;
      };
    };
    about: string;
    contact: string;
    mobile: {
      items: {
        messengerPigeon: NavItem;
        liveServices: NavItem;
        about: NavItem;
        blog: NavItem;
        contact: NavItem;
        login: NavItem;
      };
      promo: {
        label: string;
        image: ImageWithAlt;
      };
    };
  };
  footer: {
    logoAlt: string;
    columns: {
      login: {
        label: string;
        items: {
          messengerPigeon: string;
          admin: string;
        };
      };
      company: {
        label: string;
        items: {
          about: string;
          careers: string;
          security: string;
          download: string;
        };
      };
      resources: {
        label: string;
        items: {
          help: string;
          blog: string;
          grants: string;
          bookCall: string;
          partners: string;
        };
      };
      more: {
        label: string;
        items: {
          privacy: string;
          securityAi: string;
          terms: string;
          accessibility: string;
        };
      };
    };
    social: {
      youtube: string;
      linkedin: string;
      instagram: string;
      tiktok: string;
    };
    copyright: string;
  };
  links: {
    home: string;
    messengerPigeon: string;
    podium: string;
    liveServices: string;
    blog: string;
    help: string;
    security: string;
    adminLogin: string;
    apply: string;
    bookCall: string;
    messengerPigeonLogin: string;
    messengerPigeonDownload: string;
    whatsNewVideo: string;
    about: string;
    careers: string;
    contact: string;
    grants: string;
    partners: string;
    privacy: string;
    securityAi: string;
    terms: string;
    accessibility: string;
    youtube: string;
    linkedin: string;
    instagram: string;
    tiktok: string;
  };
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type HomePage = {
  _id: string;
  _type: "homePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  language?: string;
  hero: HeroSection;
  values: ValuesSection;
  products: ProductsSection;
  blog: BlogSection;
  contact: ContactSection;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type AllSanitySchemaTypes = FollowUp | Items | Form | ContactSection | BlogSection | ProductsSection | ValuesSection | HeroSection | ProductCard | NavItem | SanityImageAssetReference | ImageWithAlt | Post | SiteSettings | SanityImageCrop | SanityImageHotspot | HomePage | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageMetadata | SanityFileAsset | SanityAssetSourceData | SanityImageAsset | Geopoint | Slug;

// Source: ../habitat-rebuild-test/sanity/queries.ts
// Variable: SITE_SETTINGS_QUERY
// Query: *[_type == "siteSettings" && _id == "siteSettings-en"][0]
export type SITE_SETTINGS_QUERY_RESULT = {
  _id: "siteSettings-en";
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  language?: string;
  meta: {
    title: string;
    description: string;
    ogImage: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
  };
  nav: {
    logoAlt: string;
    openMenu: string;
    closeMenu: string;
    getStarted: string;
    organizations: {
      label: string;
      columns: {
        products: {
          label: string;
          items: {
            messengerPigeon: NavItem;
            podium: NavItem;
            liveServices: NavItem;
          };
        };
        resources: {
          label: string;
          items: {
            blog: NavItem;
            help: NavItem;
            security: NavItem;
          };
        };
        start: {
          label: string;
          items: {
            login: NavItem;
            bookCall: NavItem;
          };
        };
      };
      promo: {
        label: string;
        image: ImageWithAlt;
      };
    };
    students: {
      label: string;
      columnLabel: string;
      items: {
        messengerPigeon: string;
        help: string;
        download: string;
        helpAgain: string;
        login: string;
      };
      promo: {
        label: string;
      };
    };
    about: string;
    contact: string;
    mobile: {
      items: {
        messengerPigeon: NavItem;
        liveServices: NavItem;
        about: NavItem;
        blog: NavItem;
        contact: NavItem;
        login: NavItem;
      };
      promo: {
        label: string;
        image: ImageWithAlt;
      };
    };
  };
  footer: {
    logoAlt: string;
    columns: {
      login: {
        label: string;
        items: {
          messengerPigeon: string;
          admin: string;
        };
      };
      company: {
        label: string;
        items: {
          about: string;
          careers: string;
          security: string;
          download: string;
        };
      };
      resources: {
        label: string;
        items: {
          help: string;
          blog: string;
          grants: string;
          bookCall: string;
          partners: string;
        };
      };
      more: {
        label: string;
        items: {
          privacy: string;
          securityAi: string;
          terms: string;
          accessibility: string;
        };
      };
    };
    social: {
      youtube: string;
      linkedin: string;
      instagram: string;
      tiktok: string;
    };
    copyright: string;
  };
  links: {
    home: string;
    messengerPigeon: string;
    podium: string;
    liveServices: string;
    blog: string;
    help: string;
    security: string;
    adminLogin: string;
    apply: string;
    bookCall: string;
    messengerPigeonLogin: string;
    messengerPigeonDownload: string;
    whatsNewVideo: string;
    about: string;
    careers: string;
    contact: string;
    grants: string;
    partners: string;
    privacy: string;
    securityAi: string;
    terms: string;
    accessibility: string;
    youtube: string;
    linkedin: string;
    instagram: string;
    tiktok: string;
  };
} | null;

// Source: ../habitat-rebuild-test/sanity/queries.ts
// Variable: SITE_META_QUERY
// Query: *[_type == "siteSettings" && _id == "siteSettings-en"][0].meta
export type SITE_META_QUERY_RESULT = {
  title: string;
  description: string;
  ogImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
} | null;

// Source: ../habitat-rebuild-test/sanity/queries.ts
// Variable: SITE_LINKS_QUERY
// Query: *[_type == "siteSettings" && _id == "siteSettings-en"][0].links
export type SITE_LINKS_QUERY_RESULT = {
  home: string;
  messengerPigeon: string;
  podium: string;
  liveServices: string;
  blog: string;
  help: string;
  security: string;
  adminLogin: string;
  apply: string;
  bookCall: string;
  messengerPigeonLogin: string;
  messengerPigeonDownload: string;
  whatsNewVideo: string;
  about: string;
  careers: string;
  contact: string;
  grants: string;
  partners: string;
  privacy: string;
  securityAi: string;
  terms: string;
  accessibility: string;
  youtube: string;
  linkedin: string;
  instagram: string;
  tiktok: string;
} | null;

// Source: ../habitat-rebuild-test/sanity/queries.ts
// Variable: HOME_HERO_QUERY
// Query: *[_type == "homePage" && _id == "homePage-en"][0].hero
export type HOME_HERO_QUERY_RESULT = HeroSection | null;

// Source: ../habitat-rebuild-test/sanity/queries.ts
// Variable: HOME_VALUES_QUERY
// Query: *[_type == "homePage" && _id == "homePage-en"][0].values
export type HOME_VALUES_QUERY_RESULT = ValuesSection | null;

// Source: ../habitat-rebuild-test/sanity/queries.ts
// Variable: HOME_PRODUCTS_QUERY
// Query: *[_type == "homePage" && _id == "homePage-en"][0].products
export type HOME_PRODUCTS_QUERY_RESULT = ProductsSection | null;

// Source: ../habitat-rebuild-test/sanity/queries.ts
// Variable: HOME_BLOG_QUERY
// Query: *[_type == "homePage" && _id == "homePage-en"][0].blog
export type HOME_BLOG_QUERY_RESULT = BlogSection | null;

// Source: ../habitat-rebuild-test/sanity/queries.ts
// Variable: HOME_CONTACT_QUERY
// Query: *[_type == "homePage" && _id == "homePage-en"][0].contact
export type HOME_CONTACT_QUERY_RESULT = ContactSection | null;

// Source: ../habitat-rebuild-test/sanity/queries.ts
// Variable: HOME_POSTS_QUERY
// Query: *[_type == "post"] | order(date desc)[0...3]
export type HOME_POSTS_QUERY_RESULT = Array<{
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  category: string;
  date: string;
  image: ImageWithAlt;
  url: string;
}>;

// Query TypeMap
declare global {
  interface SanityQueries {
    "*[_type == \"siteSettings\" && _id == \"siteSettings-en\"][0]": SITE_SETTINGS_QUERY_RESULT;
    "*[_type == \"siteSettings\" && _id == \"siteSettings-en\"][0].meta": SITE_META_QUERY_RESULT;
    "*[_type == \"siteSettings\" && _id == \"siteSettings-en\"][0].links": SITE_LINKS_QUERY_RESULT;
    "*[_type == \"homePage\" && _id == \"homePage-en\"][0].hero": HOME_HERO_QUERY_RESULT;
    "*[_type == \"homePage\" && _id == \"homePage-en\"][0].values": HOME_VALUES_QUERY_RESULT;
    "*[_type == \"homePage\" && _id == \"homePage-en\"][0].products": HOME_PRODUCTS_QUERY_RESULT;
    "*[_type == \"homePage\" && _id == \"homePage-en\"][0].blog": HOME_BLOG_QUERY_RESULT;
    "*[_type == \"homePage\" && _id == \"homePage-en\"][0].contact": HOME_CONTACT_QUERY_RESULT;
    "*[_type == \"post\"] | order(date desc)[0...3]": HOME_POSTS_QUERY_RESULT;
  }
}
// Lets @sanity/client releases that predate the global registry read it too
declare module "@sanity/client" {
  interface SanityQueries extends globalThis.SanityQueries {}
}

